equipment = [
    {"equipment_id": 1, "type": "RTG", "busy": True, "current_truck": None},
    {"equipment_id": 2, "type": "RTG", "busy": False, "current_truck": None},
    {"equipment_id": 3, "type": "RTG", "busy": False, "current_truck": None},
    {"equipment_id": 4, "type": "RS", "busy": True, "current_truck": None},
    {"equipment_id": 5, "type": "RS", "busy": False, "current_truck": None},
]

trucks = [
    {
        "license_plate": "ABC1234",
        "driver": "João",
        "container_number": "MSCU 222333-3",
        "yard_block": "A",
        "equipment_needed": "RTG",
        "arrival_time": "08:00",
        "service_duration": 20,
        "departure_time": None,
        "plate_verified_on_exit": None,
    },
    {
        "license_plate": "AXF 3333",
        "driver": "Marcos",
        "container_number": "MSCU 123444-3",
        "yard_block": "B",
        "equipment_needed": "RS",
        "arrival_time": "09:00",
        "service_duration": 40,
        "departure_time": None,
        "plate_verified_on_exit": None,
    },
    {
        "license_plate": "GHI9012",
        "driver": "Alfredo",
        "container_number": "YMLU 000033-7",
        "yard_block": "C",
        "equipment_needed": "RTG",
        "arrival_time": "07:30",
        "service_duration": 15,
        "departure_time": None,
        "plate_verified_on_exit": None,
    },
    {
        "license_plate": "JKL3456",
        "driver": "Jack",
        "container_number": "HTMU 122333-3",
        "yard_block": "D",
        "equipment_needed": "RS",
        "arrival_time": "13:00",
        "service_duration": 25,
        "departure_time": None,
        "plate_verified_on_exit": None,
    },
    {
        "license_plate": "DEF5678",
        "driver": "Tiago",
        "container_number": "NXDU 222445-3",
        "yard_block": "E",
        "equipment_needed": "RTG",
        "arrival_time": "10:00",
        "service_duration": 50,
        "departure_time": None,
        "plate_verified_on_exit": None,
    },
]

